### ISSUE TITLE
Evernote::EDAM::Error::EDAMSystemException

### ISSUE THREAD

**Issue by yashwinkumar** [Evernote/evernote-oauth-ruby#12]
Gemfile
gem 'evernote_oauth'
gem 'omniauth-evernote'

omniauth.rb
  provider :evernote, EVERNOTE_CONSUMER_KEY, EVERNOTE_CONSUMER_SECRET ,:client_options => { :site => 'https://www.evernote.com' }

token = user.oauth_token
        client = EvernoteOAuth::Client.new(token: token)
        note_store = client.note_store
## Error from console

Evernote::EDAM::Error::EDAMSystemException: Evernote::EDAM::Error::EDAMSystemException
    from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/evernote-thrift-1.23.1/lib/Evernote/EDAM/user_store.rb:180:in `recv_getNoteStoreUrl'
    from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/evernote-thrift-1.23.1/lib/Evernote/EDAM/user_store.rb:169:in`getNoteStoreUrl'
    from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/evernote_oauth-0.1.6/lib/evernote_oauth/thrift_client_delegation.rb:11:in `method_missing'
    from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/evernote_oauth-0.1.6/lib/evernote_oauth/note_store.rb:8:in`note_store'
    from (irb):12
    from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.8/lib/rails/commands/console.rb:47:in `start'
    from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.8/lib/rails/commands/console.rb:8:in`start'
    from /home/startup/.rvm/gems/ruby-1.9.3-p385/gems/railties-3.2.8/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

**Comment by rekotan** [comment]
If you want to use EvernoteOAuth::Client on production, please try

``` ruby
client = EvernoteOAuth::Client.new(token: token, sandbox: false)
```

**Comment by yashwinkumar** [comment]
Thanks for fast reply.
Its working perfectly with the solution.

**Comment by xiaoronglv** [comment]
it works, thanks for your answer. @yashwinkumar
