### ISSUE TITLE
undefined local variable or method `note_store' for #<Evernote::EDAM::NoteStore::SyncChunk:0x9024b54>

### ISSUE THREAD

**Issue by pymander** [Evernote/evernote-oauth-ruby#13]
I'm getting this error quite a bit, and I'm honestly having some trouble tracking it down.  I think it's happening when I use the `notes` accessor on a SyncChunk object.

(I'm really new to Ruby, so perhaps I'm using the wrong approach.)

**Comment by rekotan** [comment]
That error doesn't occur to me. Could you provide code snippet and how you use SyncChunk?

**Comment by rekotan** [comment]
Close this for now. Please use our forum [here](http://discussion.evernote.com/forum/61-evernote-for-developers/) if you still have this issue. Thanks.
