### ISSUE TITLE
undefined local variable or method `note_store' for #<Evernote::EDAM::NoteStore::NoteList:0x007feeb2015038>  trying to access notes for a Business NoteList

### ISSUE THREAD

**Issue by alexchee** [Evernote/evernote-oauth-ruby#14]
When I try access Notes from a NoteList in a Business NoteStore, I get an undefined method error. 

Here's a snipet of code I use:
client = EvernoteOAuth::Client.new(config)
filters = Evernote::EDAM::NoteStore::NoteFilter.new
filters.notebookGuid = "NOTEBOOK GUID"
note_list = client.business_note_store.findNotes(filters, 0, 100)
note_list.notes

The NoteList class tries to look at note_store instead of business_note_store, which is correct only for a non-business NoteBook. 

My workaround is to do this:
note_list.instance_variable_get("@notes")

Is there a better way to get notes from a Business NoteList?

**Comment by rekotan** [comment]
Fixed in the latest version. Thank you for reporting this.
