### ISSUE TITLE
Request Token Authorize URL Path Error

### ISSUE THREAD

**Issue by fism88** [Evernote/evernote-oauth-ruby#9]
After calling request_token.authorize_url, I seem to be getting an incorrect url path with '/oauth/authorize' instead of '/OAuth.action' in the URL. I have sandbox set to true.

The code I have now that works is: 

```
client = EvernoteOAuth::Client.new(
  consumer_key: 'my_evernote_key',
  consumer_secret: 'my_evernote_secret',
  sandbox: true
)

request_token = client.request_token(:oauth_callback => my_callback_url)

request_token.authorize_url.gsub('/oauth/authorize', '/OAuth.action')
```

**Comment by rekotan** [comment]
Fixed this issue.  Now you don't have to gsub the URL.  Thanks.

**Comment by fism88** [comment]
Cool, thanks for fixing!
